name: clinicafx
version: '0.1.1'
summary: ClinicaFX
description: |
  Programa feito em Java / JavaFX, voltado para area da saúde.
base: core18
grade: stable
confinement: strict

parts:
  clinicafx:
    plugin: gradle
    source: .
    build-packages: 
      - libgtk-3-dev
      - openjdk-11-jdk-headless
      - ca-certificates-java
      - make
    stage-packages:
      - sqlite3
      - openjfx

  libjar:
    plugin: dump
    source: snap/local
    stage:
      - libjar
      - clinicafx.sh

apps:
  clinicafx:
    command: desktop-launch $SNAP/clinicafx.sh
    extensions: [gnome-3-28]
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - desktop
      - wayland
      - unity7
      - home
      - network
      - cups-control
