name: clinicafx
version: '0.1.0'
summary: ClinicaFX
description: |
  Programa feito em Java / JavaFX, voltado para area da saúde.
base: core18
grade: stable
confinement: strict

apps:
  clinicafx:
    command: java --module-path="$SNAP/libjar" -cp $SNAP/jar/ClinicaFX.jar clinicafx.Launcher
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - desktop
      - wayland
      - unity7

parts:
  clinicafx:
    plugin: gradle
    source: .
    build-packages: [openjdk-11-jdk]
    stage-packages:
      - sqlite3
      - openjfx


  libjar:
    plugin: dump
    source: snap/local
    stage:
      - libjar

     
